// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fibo_grid/domain/entities/grid_cell.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GridCellAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GridCellAdapter());
  }
}
